version: '3.5'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./planonline:/var/www/app
      - ./nginx_conf:/etc/nginx/conf.d
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./planonline:/var/www/app